# Generated by Django 5.0.4 on 2024-04-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_teacherattendance_student_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherattendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='teacherattendance',
            unique_together={('teacher_id', 'date')},
        ),
    ]
