# Generated by Django 5.0.4 on 2024-04-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_teacherattendance_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherattendance',
            unique_together=set(),
        ),
    ]
