# Generated by Django 5.0.4 on 2024-04-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_attendance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendance',
            new_name='TeacherAttendance',
        ),
    ]
