# Generated by Django 5.0.4 on 2024-04-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_attendance_teacherattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_type',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
