# Generated by Django 5.0.4 on 2024-04-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherattendance',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
