# Generated by Django 5.0.4 on 2024-04-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_teacherattendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherattendance',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
