# Generated by Django 5.0.4 on 2024-04-27 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_teacherattendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherattendance',
            name='teacher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher'),
        ),
    ]
