# Generated by Django 5.0.4 on 2024-04-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_teacherattendance_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherAttendance',
            new_name='TeachAttendance',
        ),
    ]
