# Generated by Django 5.0.4 on 2024-04-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_teacherattendance_teachattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachattendance',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
