# Generated by Django 5.0.4 on 2024-04-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_teachattendance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_pdf', models.BinaryField()),
            ],
        ),
    ]
