# Generated by Django 5.0.4 on 2024-04-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_coursespdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursespdf',
            name='course_pdf',
            field=models.FileField(upload_to='course_pdfs/'),
        ),
    ]
